### ISSUE TITLE
Test Failed

### ISSUE THREAD

**Issue by BilalArxd** [waqaskhan540/MapperJs#1]
**Before:**
![image](https://cloud.githubusercontent.com/assets/19899098/23569381/ccd0521a-0080-11e7-8749-bf58b62cbc74.png)

**After:** 
Replacing 
`  <script src="../src/map.js"></script>`
with _tests/index.html Line no 23_ 
`  <script src="../src/mapperjs.js"></script>`
![image](https://cloud.githubusercontent.com/assets/19899098/23569455/3af05b46-0081-11e7-867c-1aed50208122.png)

**Comment by waqaskhan540** [comment]
thanks for sharing,, its fixed now.. :)
